name: Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:

  tests:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest ] # , macos-latest, windows-latest ]
        python-version: [ "2.7", "3.6", "3.7", "3.8", "3.9" ]
        include:
        - os: ubuntu-latest
          path: ~/.cache/pip
        #- os: macos-latest
        #  path: ~/Library/Caches/pip
        #- os: windows-latest
        #  path: ~\AppData\Local\pip\Cache

    # https://docs.github.com/en/free-pro-team@latest/actions/guides/about-service-containers
    services:

      influxdb:
        image: influxdb:1.8.3
        ports:
          - 8086:8086

    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python-version }}

    name: Python ${{ matrix.python-version }} on OS ${{ matrix.os }}
    steps:

      - name: Acquire sources
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Apply caching of dependencies
        uses: actions/cache@v2
        with:
          path: ${{ matrix.path }}
          key: ${{ runner.os }}-pip-${{ hashFiles('setup.py', 'requirements-test.txt') }}
          restore-keys: |
           ${{ runner.os }}-pip-

      - name: Run tests
        run: |

          # Install tox
          # https://github.com/ymyzk/tox-gh-actions
          pip install tox tox-gh-actions

          # Run unit- and integration-tests
          tox
